---
- name: Upload Simple File
  hosts: localhost
  become: yes
  gather_facts: yes
  tasks:
    - name: Upload file
      template:
        src: .config.json
        dest: /usr/src
        mode: 0777
      register: upload_file

